### ISSUE TITLE
Installation Guide

### ISSUE THREAD

**Issue by jordanskole** [lancecarlson/React-MVC#1]
``` shell
$ cd working-directory
$ git clone https://github.com/lancecarlson/React-MVC.git
$ cd React-MVC/examples/todo
$ npm install
$ node dev
```

??

**Comment by jordanskole** [comment]
``` shell
9 verbose stack Error: todo@0.0.1 dev: `budo src/index.js --live --pushstate --verbose -o -- -t [ babelify --presets [ es2015 react ] ]`
9 verbose stack spawn ENOENT
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:17:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

via [npm-debug.log](https://gist.github.com/jordanskole/27ca25ffca648b7519fc8732fefdde65)

**Comment by lancecarlson** [comment]
Is budo installed? 

```
npm install budo -g
```

**Comment by lancecarlson** [comment]
Also, what version of node are you running?
